# Generated by Django 3.1.5 on 2021-01-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210122_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
