# Generated by Django 3.1.5 on 2021-01-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210122_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='picture',
        ),
    ]
