# Generated by Django 3.1.5 on 2021-01-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_album_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='img',
            field=models.BinaryField(null=True),
        ),
    ]
